import Head from 'next/head'
import Image from 'next/image'
import Mint from '../components/Mint'
import Faq from '../sections/Faq'
import Hero from '../sections/Hero'
import Team from '../sections/Team'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Cloud Bunnies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <main>
          <Hero />
          <Mint />
          <Team />
          <Faq />
       </main>
    </div>
  )
}
